version: '3.8'

services:
  posthog-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOMAIN=localhost
      - POSTHOG_REGION=us
      - NGINX_PORT=8080
    restart: unless-stopped